version: '2'
services:
  neon:
    build: ./wallets/neon
    command: ['neon']
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ./data/Neon:/home/developer/.config/Neon
  exodus:
    build: ./wallets/exodus
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ./data/Exodus:/home/developer/.config/Exodus
    command: ['/home/developer/exodus/Exodus']

  eidoo:
    build: ./wallets/eidoo
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - ./data/Eidoo:/home/developer/.config/eidoo
    command: ['/usr/bin/eidoo']

  
